dist: precise

language: php

services:
  - mysql

php:
  - 5.6.19
  - 7.0
  - 7.1

env:
  global:
    - TC=unit
    - SRV_HOST_NAME=localhost
    - SRV_HOST_PORT=8080

before_install:
  # Create mautictest database
  - if [[ $TC == 'unit' ]]; then mysql -e 'CREATE DATABASE mautictest;'; fi

  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

  # install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

  # install PHPSTAN for PHP 7+
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then composer global require phpstan/phpstan-shim; fi

install:
  - composer install

before_script:
  - if [[ $TC == 'selenium' ]]; then tests/setup_ui_tests.sh; fi
  - if [[ $TC == 'selenium' ]]; then tests/start_php_dev_server.sh; fi

script:

  # Run PHPUnit
  - if [[ $TC == 'unit' ]]; then bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist; fi

  # Run PHPSTAN analysis for PHP 7+
  - if [[ $TC == 'unit'  && ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then ~/.composer/vendor/phpstan/phpstan-shim/phpstan.phar analyse app/bundles/CampaignBundle app/bundles/WebhookBundle app/bundles/LeadBundle; fi

  # Check if the code standards weren't broken.
  - if [[ $TC == 'phpcs' ]]; then bin/php-cs-fixer fix -v --dry-run --diff; fi

  - if [[ $TC == 'selenium' ]]; then tests/start_ui_tests.sh; fi

matrix:
  include:
    - php: 7.1
      env: TC=selenium BROWSER="chrome" BROWSER_VERSION="latest" BEHAT_SUITE="basic" PLATFORM="Windows 10"
      addons:
        sauce_connect: true

    - php: 7.1
      env: TC=selenium BROWSER="firefox" BROWSER_VERSION="47.0" BEHAT_SUITE="basic" PLATFORM="Windows 10"
      addons:
        sauce_connect: true

    - php: 7.1
      env: TC=selenium BROWSER="chrome" BROWSER_VERSION="latest" BEHAT_SUITE="contacts" PLATFORM="Windows 10"
      addons:
        sauce_connect: true

    - php: 7.1
      env: TC=selenium BROWSER="firefox" BROWSER_VERSION="47.0" BEHAT_SUITE="contacts" PLATFORM="Windows 10"
      addons:
        sauce_connect: true

    - php: 7.1
      env: TC=phpcs
