<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'mautictest',
	'db_user' => 'travis',
	'db_password' => '',
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.7.19-0ubuntu0.16.04.1',
	'mailer_from_name' => 'Mautic Admin',
	'mailer_from_email' => 'me@somewhere.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '5333a27010183ebb324585acfdd8465a77677445e4b115b60bff00cde463a19b',
	'site_url' => 'http://localhost:8080/index.php',
);
